/*
 * Timer_config.h    
 *
 * Created: 11/1/2023 4:28:28 PM
 *  Author: Moataz Hassan, Hany El Taweel
 */

#ifndef _TIMER_CONFIG_H_
#define _TIMER_CONFIG_H_

/*
	Options:
			TIMER0_NORMAL
			TIMER0_PWM_PC
			TIMER0_CTC
			TIMER0_PWM_FAST
*/
#define TIMER0_MODE_OF_OPERATIONS TIMER0_NORMAL


/*
	Options:
			TIMER0_NO_PRESCALING
			TIMER0_DIV_BY_8
			TIMER0_DIV_BY_64
			TIMER0_DIV_BY_256
			TIMER0_DIV_BY_1024
			TIMER0_EXTERNAL_FALIING
			TIMER0_EXTERNAL_RISING
*/
#define TIMER0_CLOCK_SELECTIONS TIMER0_DIV_BY_1024

/*
	Options:
			TIMER1_NO_PRESCALING
			TIMER1_DIV_BY_8
			TIMER1_DIV_BY_64
			TIMER1_DIV_BY_256
			TIMER1_DIV_BY_1024
			TIMER1_EXTERNAL_FALIING
			TIMER1_EXTERNAL_RISING
*/
#define TIMER1_CLOCK_SELECTIONS TIMER1_DIV_BY_1024

/*
	Options:
			TIMER2_NO_PRESCALING
			TIMER2_DIV_BY_8
			TIMER2_DIV_BY_32
			TIMER2_DIV_BY_64
			TIMER2_DIV_BY_128
			TIMER2_DIV_BY_256
			TIMER2_DIV_BY_1024
*/
#define TIMER2_CLOCK_SELECTIONS TIMER2_DIV_BY_1024


#endif

/*
 * Timer_config.h    
 *
 * Created: 11/1/2023 4:28:28 PM
 *  Author: Moataz Hassan, Hany El Taweel
 */